export const CATEGORY_LABELS: Record<string, string> = {
  parfum: "Parfum",
  bijou: "Bijou",
  montre: "Montre",
  jouet: "Jouet",
  chocolat: "Chocolat",
  bougie: "Bougie",
  coffret: "Coffret",
  livre: "Livre",
  tech: "Tech",
  maquillage: "Maquillage",
  beaute: "Beauté",
  the_cafe: "Thé / Café",
  alcool: "Alcool",
  deco: "Déco",
  cuisine: "Cuisine",
  maroquinerie: "Maroquinerie",
  mode: "Mode",
  jeu_video: "Jeu vidéo",
  sport: "Sport",
  papeterie: "Papeterie",
  bebe: "Bébé",
  autre: "Autre",
};
